TwilioSID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
TwilioToken: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
TwilioNumber: +15030000000
YourMobile: +15030000000
YourETHAddress: 0x0000000000000000000000000000000000000000
ETHWithdrawalFee: 0.01
PoloniexAPIKey: XXXXXXXX-XXXXXXXX-X0XXXXXX-XXXXXXXX
PoloniexAPISecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
BTCPerRun: 0.042
